<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PerformativeMail.Game</RootNamespace>
    <AssemblyName>PerformativeMail</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\src\App\PerformativeMail.App.csproj" />
  </ItemGroup>
</Project>
